default_language_version:
  python: python3
fail_fast: false
minimum_pre_commit_version: 4.1.0
repos:
- hooks:
  - id: check-json
  - exclude: ^.github/ISSUE_TEMPLATE/
    id: check-yaml
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: detect-private-key
  - args:
    - --branch
    - main
    id: no-commit-to-branch
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: b89c5eef3ba3a74ecd506d968e63a8b80f697abf
- hooks:
  - args:
    - --fix
    id: markdownlint
    stages:
    - manual
  repo: https://github.com/igorshubovych/markdownlint-cli
  rev: 70466ee0aa1d9bca1fd4ce54bfbba370431ecced
- hooks:
  - exclude: ^(\.github/|workflows/|templates/)
    id: yaml-sorter
  - id: json-sorter
  - id: env-file-check
  - id: env-example-sync
  repo: https://github.com/chrysa/pre-commit-tools
  rev: 04936a6cf718400fe9d2fd883c188fdf4d09eba2
