default_language_version:
  python: python3
fail_fast: false
minimum_pre_commit_version: 4.1.0
repos:
- hooks:
  - id: check-json
  - exclude: ^.github/ISSUE_TEMPLATE/
    id: check-yaml
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: detect-private-key
  - args:
    - --branch
    - main
    id: no-commit-to-branch
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: b89c5eef3ba3a74ecd506d968e63a8b80f697abf
- hooks:
  - args:
    - --fix
    id: markdownlint
    stages:
    - manual
  repo: https://github.com/igorshubovych/markdownlint-cli
  rev: cfc833bfc00c7cc40f702bd9e02df34d850d0291
- hooks:
  - exclude: ^(\.github/|workflows/|templates/)
    id: yaml-sorter
  - id: json-sorter
  - id: env-file-check
  repo: https://github.com/chrysa/pre-commit-tools
  rev: e538371cdb5dff59d3b67ef5e63dae3dce8bfc37
