sonar.projectKey=chrysa_shared-standards
sonar.organization=chrysa
sonar.projectName=shared-standards
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.mypy_cache/**
