"on":
  pull_request:
    branches-ignore:
      - develop
      - main
      - master
    types:
      - auto_merge_enabled
      - opened
      - ready_for_review
      - reopened
      - synchronize
  schedule:
    - cron: 0 0 * * *
  workflow_call:
  workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  extract_dependencies:
    name: Extract dependent Pull Requests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: depends-on/depends-on-action@c7ac9a6932a7069e83aef80c202d9f60f91e43fd # 0.17.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  check_dependencies_merged:
    name: Check dependent Pull Requests are merged
    runs-on: ubuntu-latest
    steps:
      - uses: depends-on/depends-on-action@c7ac9a6932a7069e83aef80c202d9f60f91e43fd # 0.17.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check-unmerged-pr: true
name: Check PR dependencies
permissions:
  contents: read
  pull-requests: write
run-name: ${{ github.workflow }} by ${{ github.actor }}
